In [37]:
import pandas as pd

In [38]:
df_peyman = pd.read_excel("assets/data/peyman.xlsx", sheet_name=None)

In [41]:
df = pd.DataFrame()

for region, data in df_peyman.items():
    data["منطقه"] = region
    df = pd.concat([df, data])

df = df[["منطقه", "نام پیمان", "نام لکه", "شناسه لکه", "نوع لکه"]]




df.drop_duplicates(subset=['نام پیمان'], keep='last')
# df_peyman[list(df_peyman.keys())[1]]

,منطقه,نام پیمان,نام لکه,شناسه لکه,نوع لکه
94,منطقه1,الف ناحیه 1 منطقه 1,آیلند خیابان دانشگاه,2324,آیلند ها
160,منطقه1,ناحیه 3 منطقه 1 - 9711,آیلند بلوار مجد,234,آیلند ها
236,منطقه1,ب ناحیه 2 منطقه 1 - 9808,آیلند بلوار ملک آباد,587,آیلند ها
307,منطقه1,الف ناحیه 2 منطقه 1 - 9808,آیلند نوربخش 13,190,آیلند ها
48,منطقه2,الف ناحیه 2 منطقه 2,کنار گذرهای صدمتری حدفاصل میدان امام حسین(ع) ت...,1942,حاشیه های بزرگراه
...,...,...,...,...,...
83,منطقه12,ناحیه 2 منطقه 12 - 9712,حاشیه بزرگراه آیت ا... رفسنجانی حدفاصل بلوار ش...,2686,حاشیه های بزرگراه
189,منطقه12,ناحیه 1 منطقه 12 - 9812,حاشیه بزرگراه هاشمی رفسنجانی,671,حاشیه های بزرگراه
203,منطقه12,ناحیه 3 منطقه 12 - 9907,آیلند بلوار پردیس,2725,آیلند ها
41,منطقه ثامن,ناحیه 2 منطقه ثامن,شهید شوشتری,2552,آیلند ها
71,منطقه ثامن,ناحیه 1 منطقه ثامن - 9812,آیلند بلوار شارستان رضوی,2703,آیلند ها

In [17]:
import pandas as pd

df = pd.read_csv("C://Users/pooya/Desktop/Precipitation/ERA5-Land_Monthly_Averaged.csv")

df["date"] = df["system:index"].str.split("_", 1, expand=True)[0]
df["year"] = df["date"].apply(lambda x : x[0:4])
df["month"] = df["date"].apply(lambda x : x[4:6])
# df["day"] = df["date"].apply(lambda x : x[6:8])

df.groupby(["geeID", "year"])["mean"].sum().reset_index()

    geeID  year      mean
0       0  2001  0.012391
1       0  2002  0.013236
2       0  2003  0.009019
3       0  2004  0.011978
4       0  2005  0.009605
5       0  2006  0.011146
6       0  2007  0.008542
7       0  2008  0.005390
8       0  2009  0.009244
9       0  2010  0.006518
10      0  2011  0.009220
11      0  2012  0.011823
12      0  2013  0.008667
13      0  2014  0.010995
14      1  2001  0.022558
15      1  2002  0.027812
16      1  2003  0.022060
17      1  2004  0.023768
18      1  2005  0.021239
19      1  2006  0.024559
20      1  2007  0.020230
21      1  2008  0.010690
22      1  2009  0.019853
23      1  2010  0.013161
24      1  2011  0.022082
25      1  2012  0.018796
26      1  2013  0.014083
27      1  2014  0.016903
28      2  2001  0.005889
29      2  2002  0.005224
30      2  2003  0.004717
31      2  2004  0.006774
32      2  2005  0.005690
33      2  2006  0.005798
34      2  2007  0.004469
35      2  2008  0.002897
36      2  2009  0.004991
37      2  2010  0.001642
38      2  2011  0.004262
39      2  2012  0.005819
40      2  2013  0.008784
41      2  2014  0.004815
42      3  2001  0.010240
43      3  2002  0.012807
44      3  2003  0.010437
45      3  2004  0.016144
46      3  2005  0.010834
47      3  2006  0.011047
48      3  2007  0.008776
49      3  2008  0.005673
50      3  2009  0.012270
51      3  2010  0.003608
52      3  2011  0.008731
53      3  2012  0.012414
54      3  2013  0.008203
55      3  2014  0.011613

In [13]:
df

                        system:index  geeID  mean      date  year month day
0      20010101_00000000000000000000      0   0.0  20010101  2001    01  01
1      20010101_00000000000000000001      1   0.0  20010101  2001    01  01
2      20010101_00000000000000000002      2   0.0  20010101  2001    01  01
3      20010101_00000000000000000003      3   0.0  20010101  2001    01  01
4      20010102_00000000000000000000      0   0.0  20010102  2001    01  02
...                              ...    ...   ...       ...   ...   ...  ..
20367  20141230_00000000000000000003      3   0.0  20141230  2014    12  30
20368  20141231_00000000000000000000      0   0.0  20141231  2014    12  31
20369  20141231_00000000000000000001      1   0.0  20141231  2014    12  31
20370  20141231_00000000000000000002      2   0.0  20141231  2014    12  31
20371  20141231_00000000000000000003      3   0.0  20141231  2014    12  31

[20372 rows x 7 columns]

In [2]:
import pandas as pd
%config Completer.use_jedi = False

In [38]:
df = pd.read_excel("assets/report/Tree.xlsx")
df

,منطقه,ناحیه,پیمان,آدرس,نام نوع لکه,نام نوع قلم,نام زیرمجموعه هر قلم,مساحت آدرس مترمربع,مساحت آیتم مترمربع,مقدار آیتم خام,Atree m2,Ks,Kmc,Kd,KL,PET mm/d,Eff,Eff_Pr mm/d,Daily Irri. Req. mm/d,Tree Req. lit/d
0,4,2,1,3,حاشیه های بزرگراه,درخت و درختچه,آبیاری ثقلی,25512.0,5031.0,195,9.0,0.5,1.3,0.65,0.4225,8.738693,0.55,0,6.712905,60.416143
1,11,1,2,1,پارک های بالای 10 هکتار,درخت و درختچه,آبیاری ثقلی,601129.0,201735.0,9360,9.0,0.5,1.1,0.65,0.3575,8.738693,0.55,0,5.680150,51.121352
2,3,2,1,15,پارک های زیر 6 هکتار,درخت و درختچه,آبیاری ثقلی,27339.0,19359.0,1234,9.0,0.5,1.1,0.65,0.3575,8.738693,0.55,0,5.680150,51.121352
3,3,3,1,15,آیلند های بزرگراه,درخت و درختچه,آبیاری ثقلی,10865.0,6435.0,457,9.0,0.5,1.3,0.65,0.4225,8.738693,0.55,0,6.712905,60.416143
4,9,3,2,10,پارک های بالای 10 هکتار,درخت و درختچه,آبیاری ثقلی,52181.0,32607.0,3432,9.0,0.5,1.1,0.65,0.3575,8.738693,0.55,0,5.680150,51.121352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1701,9,2,1,16,پارک های زیر 6 هکتار,درخت و درختچه,آبیاری شلنگی,NaN,NaN,210,0.0,0.5,1.1,0.65,0.3575,8.738693,0.70,0,4.462975,0.000000
1702,10,3,2,13,پارک های زیر 6 هکتار,درخت و درختچه,آبیاری ثقلی,NaN,NaN,278,0.0,0.5,1.1,0.65,0.3575,8.738693,0.55,0,5.680150,0.000000
1703,10,3,2,24,لچکی ها,درخت و درختچه,آبیاری تانکری,NaN,NaN,44,0.0,0.5,1.3,0.65,0.4225,8.738693,0.60,0,6.153496,0.000000
1704,12,2,1,13,جنگل کاری داخل محدوده,درخت و درختچه,آبیاری ثقلی,13854.0,0.0,587,0.0,0.5,1.0,0.65,0.3250,8.738693,0.55,0,5.163773,0.000000
1705,12,2,1,68,پارک های زیر 6 هکتار,درخت و درختچه,آبیاری شلنگی,NaN,NaN,25,0.0,0.5,1.1,0.65,0.3575,8.738693,0.70,0,4.462975,0.000000

In [45]:
on=["نام زیرمجموعه هر قلم"]
a = pd.merge(left = df.groupby(on)["مقدار آیتم خام"].sum().reset_index(),
         right=df.assign(col=df["Tree Req. lit/d"] * df["مقدار آیتم خام"]).groupby(on).col.sum().reset_index(),
         how="outer",
         on=on)

a.assign(result=a["col"] / a["مقدار آیتم خام"])#.pivot(index="منطقه", columns=["نام نوع لکه"],values="result")

  نام زیرمجموعه هر قلم  مقدار آیتم خام           col     result
0        آبیاری تانکری          226210  5.850038e+06  25.861094
1      آبیاری تحت فشار          182753  4.202010e+06  22.992840
2          آبیاری ثقلی         1778481  1.180774e+07   6.639227
3         آبیاری شلنگی          534969  1.591118e+07  29.742244

In [30]:
df.groupby(on).sum().reset_index()

,منطقه,نام زیرمجموعه هر قلم,ناحیه,پیمان,آدرس,مساحت آدرس مترمربع,مساحت آیتم مترمربع,مقدار آیتم خام,Atree m2,Ks,Kmc,Kd,KL,PET mm/d,Eff,Eff_Pr mm/d,Daily Irri. Req. mm/d,Tree Req. lit/d
0,1,آبیاری تانکری,223,137,4552,47887.00,3.136395e+04,11837,279.445328,56.0,145.6,72.67,47.2355,978.733569,67.20,0,687.960856,1708.489424
1,1,آبیاری تحت فشار,1,1,2,16254.00,2.187000e+03,243,9.000000,0.5,1.3,0.52,0.3380,8.738693,0.85,0,3.474915,31.274239
2,1,آبیاری شلنگی,212,128,3357,355244.00,3.619349e+04,6372,748.513903,54.0,133.6,62.53,38.8505,943.778799,75.60,0,485.003680,3192.399453
3,2,آبیاری تانکری,175,118,1317,333816.00,1.452429e+05,23862,440.311669,40.0,100.1,49.01,30.7320,699.095406,48.00,0,447.595834,2337.081015
4,2,آبیاری تحت فشار,39,23,413,239080.00,8.971278e+04,14203,143.747620,9.0,22.8,10.27,6.5195,157.296466,15.30,0,67.025772,523.950103
5,2,آبیاری ثقلی,7,3,55,43352.00,1.989000e+04,31574,3.922802,1.0,2.1,1.30,0.6825,17.477385,1.10,0,10.843923,22.023401
6,2,آبیاری شلنگی,178,122,1577,858101.00,2.352889e+05,29170,630.714154,38.0,91.9,41.47,25.1615,664.140636,53.20,0,314.112305,2545.958535
7,3,آبیاری تانکری,41,19,258,60823.00,2.406069e+04,4526,105.352431,9.5,24.7,11.57,7.5205,166.035159,11.40,0,109.532229,581.828011
8,3,آبیاری تحت فشار,5,4,44,78735.00,8.807804e+03,1124,23.914632,1.5,3.7,1.69,1.0465,26.216078,2.55,0,10.758873,83.428114
9,3,آبیاری ثقلی,25,9,130,82934.00,3.830600e+04,10057,64.979218,4.5,10.6,5.59,3.2760,78.648233,4.95,0,52.050831,374.710704
10,3,آبیاری شلنگی,118,47,674,1095480.24,2.538884e+05,29117,354.306537,22.0,52.1,24.05,14.2805,384.502474,30.80,0,178.275571,1397.870527
11,4,آبیاری تانکری,56,25,340,68863.00,2.995202e+04,7756,119.076474,12.5,32.5,15.60,10.1400,218.467315,15.00,0,147.683905,677.355145
12,4,آبیاری تحت فشار,3,1,11,9043.00,1.638000e+03,182,9.000000,0.5,1.1,0.52,0.2860,8.738693,0.85,0,2.940313,26.462817
13,4,آبیاری ثقلی,6,4,26,174693.00,4.964655e+04,6147,39.368265,2.0,5.0,2.60,1.6250,34.954770,2.20,0,25.818864,256.058005
14,4,آبیاری شلنگی,70,32,341,669361.00,1.336143e+05,16122,233.033590,16.0,38.8,18.20,11.1020,279.638163,22.40,0,138.595664,957.444760
15,5,آبیاری تانکری,66,75,1488,43990.00,2.758857e+04,6830,220.826276,23.5,60.9,29.64,19.2010,410.718551,28.20,0,279.652727,1277.524191
16,5,آبیاری تحت فشار,2,1,1,38947.00,3.262893e+04,7250,4.500542,0.5,1.3,0.65,0.4225,8.738693,0.85,0,4.343644,19.548754
17,5,آبیاری شلنگی,65,63,1601,459846.00,1.301295e+05,26969,338.310867,21.5,52.1,24.31,14.7745,375.763781,30.10,0,184.442591,1408.567833
18,6,آبیاری تانکری,35,35,279,87387.00,2.860175e+04,5372,148.131270,11.5,28.9,13.65,8.6125,200.989929,13.80,0,125.436650,766.681354
19,6,آبیاری تحت فشار,8,5,62,255937.00,5.649300e+04,6277,36.000000,2.0,4.8,2.08,1.2480,34.954770,3.40,0,12.830457,115.474112
20,6,آبیاری ثقلی,5,10,90,30489.00,1.895987e+04,7243,20.537857,2.5,5.9,3.12,1.8460,43.693463,2.75,0,29.330230,112.667050
21,6,آبیاری شلنگی,76,68,724,740402.00,1.459429e+05,18768,358.851989,23.0,55.0,26.00,15.5870,401.979859,32.20,0,194.585716,1467.499996
22,7,آبیاری تانکری,120,93,1233,2680569.80,1.861895e+05,26764,385.144606,28.5,71.9,34.06,21.5670,498.105477,34.20,0,314.112305,2040.253086
23,7,آبیاری تحت فشار,23,22,248,1579525.00,4.466397e+05,53002,119.373069,7.0,17.1,7.67,4.6800,122.341696,11.90,0,48.114213,407.797093
24,7,آبیاری ثقلی,23,40,147,2911489.80,1.519878e+06,1489872,17.143792,6.0,13.2,7.80,4.2900,104.864311,6.60,0,68.161802,100.436124
25,7,آبیاری شلنگی,179,142,2352,2634368.00,5.389727e+05,65498,780.457933,48.5,117.3,53.56,32.4545,847.653180,68.05,0,404.584209,3163.618579
26,8,آبیاری تانکری,56,24,433,93144.00,4.677029e+04,7664,111.620963,12.0,30.9,15.08,9.7240,209.728622,14.40,0,141.625078,632.329710
27,8,آبیاری تحت فشار,24,14,107,625759.00,1.625834e+05,22073,66.736964,5.0,12.2,5.72,3.5100,87.386926,8.50,0,36.085660,223.724586
28,8,آبیاری شلنگی,134,76,1386,1229897.50,3.325109e+05,41776,449.189202,35.5,87.6,41.86,25.9610,620.447173,49.85,0,323.520352,1913.292422
29,9,آبیاری تانکری,115,114,1229,506152.00,1.381990e+05,22993,390.943499,31.0,78.0,37.70,23.7965,541.798940,37.20,0,346.583830,2098.196971
30,9,آبیاری تحت فشار,20,19,89,325747.00,1.435569e+05,19275,73.550957,4.5,11.1,5.07,3.1135,78.648233,7.65,0,32.009317,256.915600
31,9,آبیاری ثقلی,49,35,385,563127.00,2.616034e+05,113691,43.439698,10.0,21.5,13.00,6.9875,174.773852,11.00,0,111.021117,247.462471
32,9,آبیاری شلنگی,216,226,1704,3595420.00,1.341376e+06,153213,930.384437,56.5,130.0,62.92,36.3090,987.472262,79.10,0,453.275984,3654.497401
33,10,آبیاری تانکری,43,34,367,217880.00,7.486904e+04,9144,113.553178,8.5,22.1,9.88,6.4220,148.557774,10.20,0,93.533140,599.062394
34,10,آبیاری تحت فشار,20,28,179,303414.00,1.537234e+05,18354,109.711401,6.5,16.1,7.41,4.5955,113.603004,11.05,0,47.245484,395.906818
35,10,آبیاری ثقلی,4,6,20,33364.00,3.670040e+04,29958,1.236536,1.0,2.4,1.30,0.7800,17.477385,1.10,0,12.393055,8.300751
36,10,آبیاری شلنگی,406,387,4811,1397862.00,4.229426e+05,58525,1521.827003,101.5,247.8,115.18,70.6355,1773.954594,142.10,0,881.802743,6333.805471
37,11,آبیاری تانکری,63,58,1166,186236.00,1.091401e+05,16005,229.160056,19.0,48.2,23.40,14.8785,332.070318,22.80,0,216.697729,1264.439641
38,11,آبیاری ثقلی,2,3,31,607501.00,2.059680e+05,12794,22.785558,1.0,2.1,1.30,0.6825,17.477385,1.10,0,10.843923,128.788866
39,11,آبیاری شلنگی,64,53,833,976099.00,9.698115e+04,11844,304.268447,18.0,43.0,19.50,11.6740,314.592933,25.20,0,145.736425,1209.909635
40,12,آبیاری تانکری,96,69,2736,215329.00,1.842142e+05,28284,451.735299,34.5,86.5,42.25,26.5785,602.969788,41.40,0,387.102235,2446.673202
41,12,آبیاری تحت فشار,12,8,60,194825.00,8.391720e+04,10752,68.441207,4.0,10.2,4.29,2.7365,69.909541,6.80,0,28.133450,237.742918
42,12,آبیاری ثقلی,40,20,421,127988.00,6.406176e+04,57145,27.702959,10.0,20.6,13.00,6.6950,174.773852,11.00,0,106.373722,145.755637
43,12,آبیاری شلنگی,109,68,2709,633408.50,3.116008e+05,42234,538.136282,34.0,82.9,38.09,23.2700,594.231095,47.60,0,290.499109,2236.305668
44,13,آبیاری تانکری,7,6,57,6401.00,2.042631e+03,686,23.935264,3.0,7.8,3.90,2.5350,52.432155,3.60,0,36.920976,147.285550
45,13,آبیاری تحت فشار,1,1,11,2522.00,1.152633e+02,18,6.403516,0.5,1.3,0.65,0.4225,8.738693,0.85,0,4.343644,27.814594
46,13,آبیاری شلنگی,46,26,447,63803.00,1.142898e+04,1625,212.291418,13.0,30.0,14.17,8.1965,227.206007,18.20,0,102.323848,808.047348
47,16,آبیاری تانکری,7,1,1,82094.00,7.656327e+04,54487,1.405166,0.5,1.1,0.65,0.3575,8.738693,0.60,0,5.206804,7.316423
48,16,آبیاری تحت فشار,7,1,2,174768.00,6.570226e+04,30000,2.190075,0.5,1.1,0.65,0.3575,8.738693,0.85,0,3.675391,8.049383
49,16,آبیاری ثقلی,7,1,2,174768.00,4.380150e+04,20000,2.190075,0.5,1.1,0.65,0.3575,8.738693,0.55,0,5.680150,12.439956
50,16,آبیاری شلنگی,14,2,3,256862.00,7.079497e+04,33736,3.595241,1.0,2.2,1.30,0.7150,17.477385,1.40,0,8.925950,16.045471

In [1]:
z1 = "پويا"
z2 = "پویا"

z1 == z2

False

In [2]:
z1.replace('ي', 'ی') == z2

True

In [3]:
import pandas as pd

In [5]:
df = pd.DataFrame({'A' : ['پويا', 'علئان'],
                  'B' : [1, 2],
                  'C' : ['پويالالالالا', 'علئانلالا']})

df

       A  B             C
0   پويا  1  پويالالالالا
1  علئان  2     علئانلالا

In [9]:
df.replace('ئ', 'ی', regex=True)

       A  B             C
0   پويا  1  پويالالالالا
1  علیان  2     علیانلالا